# -*- coding: utf-8 -*-
"""lstm_prep.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o5swZn0NV3_dVqvqUB0JjBiYniNCdSKc
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 1. Load the cross-sectional data
df = pd.read_csv('Processed_Dataset.csv')

# LSTM ke liye humein 3 saal ka past data chahiye (Time Steps = 3)
TIME_STEPS = 3

# Sequence lists
X_sequences = []
y_targets = []

# Har player ke liye pichle 3 saal ka data simulate karenge
for index, row in df.iterrows():
    player_sequence = []

    # Current values
    curr_value = row['current_value_eur']
    cagr = row['value_cagr'] if row['value_cagr'] != 0 else 0.05 # Growth rate
    curr_age = row['age']
    perf = row['performance_efficiency']
    injury = row['injury_risk_index']

    # Generate past 3 years data by reverse engineering CAGR
    for t in range(TIME_STEPS, 0, -1):
        # Pichle saalon ki value kam hogi (based on CAGR)
        past_value = curr_value / ((1 + abs(cagr)) ** t)
        past_age = curr_age - t

        # Features: [Value, Age, Performance, Injury]
        # Performance aur injury ko past mein thoda vary kar dete hain for realism
        step_features = [
            past_value,
            past_age,
            perf * np.random.uniform(0.9, 1.1), # Slight variation
            injury * np.random.uniform(0.9, 1.1)
        ]
        player_sequence.append(step_features)

    X_sequences.append(player_sequence)
    # Target is the current value (jo hum predict karna chahte hain)
    y_targets.append(curr_value)

# Convert to Numpy Arrays (LSTM requires 3D arrays)
X_seq_array = np.array(X_sequences)
y_target_array = np.array(y_targets)

print("✅ Time-Series Data Created Successfully!")
print(f"Input Shape (X): {X_seq_array.shape} -> (Samples, Time-Steps, Features)")
print(f"Target Shape (y): {y_target_array.shape} -> (Samples, Target)")

# Saving sequences for LSTM training later
np.save('X_lstm_data.npy', X_seq_array)
np.save('y_lstm_target.npy', y_target_array)
print("💾 Saved as X_lstm_data.npy and y_lstm_target.npy")