# -*- coding: utf-8 -*-
"""train_lstm.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AR03bfTnGiIAfYMOvdj0oBvIAMVA7Ajj
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

X_train = np.load('X_lstm_data.npy')
y_train = np.load('y_lstm_target.npy')

time_steps = X_train.shape[1]
features = X_train.shape[2]

model = Sequential()

model.add(LSTM(units=64, return_sequences=True, input_shape=(time_steps, features)))
model.add(Dropout(0.2))

model.add(LSTM(units=32, return_sequences=False))
model.add(Dropout(0.2))

model.add(Dense(units=1, activation='linear'))

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

print("Starting LSTM Training...")
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

model.save('transferiq_lstm.keras')
print("Model saved successfully as 'transferiq_lstm.keras'")