# -*- coding: utf-8 -*-
"""train_xgboost.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LuyMlI29EnF-lScdkW_yjVRH1kSEtUl5
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

df = pd.read_csv('Optimized_Processed_Dataset.csv')

target_col = 'current_value_eur'
data = df[[target_col]].values

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

time_steps = 5
X, y = [], []

for i in range(len(scaled_data) - time_steps):
    X.append(scaled_data[i:(i + time_steps), 0])
    y.append(scaled_data[i + time_steps, 0])

X, y = np.array(X), np.array(y)

X = np.reshape(X, (X.shape[0], X.shape[1], 1))

model = Sequential()
model.add(LSTM(50, return_sequences=False, input_shape=(X.shape[1], 1)))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

df = pd.read_csv('Optimized_Processed_Dataset.csv')

target_data = df[['current_value_eur']].values

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(target_data)

def create_sequences(data, time_steps):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:(i + time_steps), 0])
        y.append(data[i + time_steps, 0])
    return np.array(X), np.array(y)

time_steps = 5
X, y = create_sequences(scaled_data, time_steps)

X = np.reshape(X, (X.shape[0], X.shape[1], 1))

train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(50, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(25))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')

import matplotlib.pyplot as plt

history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_data=(X_test, y_test),
    verbose=1
)

plt.figure(figsize=(10, 6))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Mean Squared Error')
plt.legend()
plt.show()

import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt

# 1. Generate predictions using the trained model
train_predict = model.predict(X_train)
test_predict = model.predict(X_test)

# 2. Inverse transform predictions to original scale (Euros)
train_predict = scaler.inverse_transform(train_predict)
test_predict = scaler.inverse_transform(test_predict)
y_test_actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# 3. Calculate evaluation metrics (RMSE & MAE)
rmse = np.sqrt(mean_squared_error(y_test_actual, test_predict))
mae = mean_absolute_error(y_test_actual, test_predict)

print(f"✅ Model Evaluation Metrics:")
print(f"📊 Root Mean Squared Error (RMSE): €{rmse:,.2f}")
print(f"📊 Mean Absolute Error (MAE): €{mae:,.2f}")

# 4. Plot Actual vs Predicted values for visual comparison
plt.figure(figsize=(12,6))
plt.plot(y_test_actual, color='blue', label='Actual Transfer Value', alpha=0.6)
plt.plot(test_predict, color='red', label='Predicted Transfer Value', alpha=0.6)
plt.title('Player Transfer Value Prediction')
plt.xlabel('Players (Test Samples)')
plt.ylabel('Transfer Value (EUR)')
plt.legend()
plt.show()

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout

df = pd.read_csv('Optimized_Processed_Dataset.csv')
features = ['current_value_eur', 'performance_efficiency', 'injury_risk_index', 'sentiment_score', 'age']
data = df[features].values

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

def create_multivariate_sequences(data, time_steps):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:(i + time_steps), :])
        y.append(data[i + time_steps, 0])
    return np.array(X), np.array(y)

time_steps = 5
X, y = create_multivariate_sequences(scaled_data, time_steps)

train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

model_multi = Sequential()
model_multi.add(Input(shape=(X_train.shape[1], X_train.shape[2])))
model_multi.add(LSTM(64, return_sequences=True))
model_multi.add(Dropout(0.2))
model_multi.add(LSTM(32, return_sequences=False))
model_multi.add(Dropout(0.2))
model_multi.add(Dense(16))
model_multi.add(Dense(1))

model_multi.compile(optimizer='adam', loss='mean_squared_error')

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error

# 1. Train the model
history_multi = model_multi.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_data=(X_test, y_test),
    verbose=1
)

# 2. Plot Loss Curves
plt.figure(figsize=(10, 6))
plt.plot(history_multi.history['loss'], label='Train Loss')
plt.plot(history_multi.history['val_loss'], label='Validation Loss')
plt.title('Multivariate Model Loss Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Mean Squared Error')
plt.legend()
plt.show()

# 3. Generate Predictions
test_predict_multi = model_multi.predict(X_test)

# 4. Inverse Transform for Multivariate Data
# We need a dummy array because the scaler was fit on 5 features, but prediction is 1 feature
dummy_pred = np.zeros((len(test_predict_multi), len(features)))
dummy_pred[:, 0] = test_predict_multi[:, 0]
test_predict_actual = scaler.inverse_transform(dummy_pred)[:, 0]

dummy_actual = np.zeros((len(y_test), len(features)))
dummy_actual[:, 0] = y_test
y_test_actual = scaler.inverse_transform(dummy_actual)[:, 0]

# 5. Evaluate Metrics
rmse_multi = np.sqrt(mean_squared_error(y_test_actual, test_predict_actual))
mae_multi = mean_absolute_error(y_test_actual, test_predict_actual)

print(f"✅ Multivariate Model Evaluation:")
print(f"📊 RMSE: €{rmse_multi:,.2f}")
print(f"📊 MAE: €{mae_multi:,.2f}")

# XGBoost library import kar rahe hain
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# XGBoost ko LSTM wale 3D sequences ki zaroorat nahi hoti, toh hum sidha 2D tabular features use karenge
X_tabular = df[['performance_efficiency', 'injury_risk_index', 'sentiment_score', 'age']].values
y_tabular = df['current_value_eur'].values

# Data ko 80-20 ratio mein split kar rahe hain
X_train_xgb, X_test_xgb, y_train_xgb, y_test_xgb = train_test_split(X_tabular, y_tabular, test_size=0.2, random_state=42)

# XGBoost model initialize kar rahe hain with specific hyperparameters
xgb_model = xgb.XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

# Model ko train kar rahe hain
xgb_model.fit(X_train_xgb, y_train_xgb)

# Test data par predictions nikal rahe hain
xgb_predictions = xgb_model.predict(X_test_xgb)

# RMSE aur MAE errors calculate kar rahe hain
xgb_rmse = np.sqrt(mean_squared_error(y_test_xgb, xgb_predictions))
xgb_mae = mean_absolute_error(y_test_xgb, xgb_predictions)

print(f"✅ XGBoost Model Evaluation:")
print(f"🌲 RMSE: €{xgb_rmse:,.2f}")
print(f"🌲 MAE: €{xgb_mae:,.2f}")

from sklearn.model_selection import GridSearchCV

# Hyperparameter grid define kar rahe hain alag-alag combinations ke saath
param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'n_estimators': [100, 200, 300]
}

# GridSearchCV setup kar rahe hain 3-fold cross-validation ke saath
grid_search = GridSearchCV(
    estimator=xgb.XGBRegressor(random_state=42),
    param_grid=param_grid,
    scoring='neg_mean_squared_error',
    cv=3,
    verbose=1
)

# Grid search ko training data par run kar rahe hain
grid_search.fit(X_train_xgb, y_train_xgb)

# Sabse best parameter combination print kar rahe hain
print("✅ Best Parameters found by GridSearchCV:")
print(grid_search.best_params_)

# Final optimized parameters ke saath model initialize kar rahe hain
best_xgb = xgb.XGBRegressor(
    learning_rate=0.1,
    max_depth=3,
    n_estimators=100,
    random_state=42
)

# Model ko train kar rahe hain
best_xgb.fit(X_train_xgb, y_train_xgb)

# Final predictions nikal rahe hain
final_predictions = best_xgb.predict(X_test_xgb)

# Final errors calculate kar rahe hain
final_rmse = np.sqrt(mean_squared_error(y_test_xgb, final_predictions))
final_mae = mean_absolute_error(y_test_xgb, final_predictions)

print(f"✅ Final Tuned XGBoost Model Performance:")
print(f"🏆 Final RMSE: €{final_rmse:,.2f}")
print(f"🏆 Final MAE: €{final_mae:,.2f}")

import matplotlib.pyplot as plt
import xgboost as xgb

# 1. Actual vs Predicted ka Scatter Plot banayenge
plt.figure(figsize=(10, 6))
plt.scatter(y_test_xgb, final_predictions, alpha=0.6, color='dodgerblue')
# Ek perfect prediction line draw kar rahe hain (Red dashed line)
plt.plot([y_test_xgb.min(), y_test_xgb.max()], [y_test_xgb.min(), y_test_xgb.max()], 'r--', lw=2)
plt.title('Actual vs Predicted Player Transfer Values')
plt.xlabel('Actual Value (EUR)')
plt.ylabel('Predicted Value (EUR)')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# 2. XGBoost Feature Importance Plot banayenge
plt.figure(figsize=(10, 6))
xgb.plot_importance(best_xgb, importance_type='weight', max_num_features=5, title='Top Factors Influencing Transfer Value')
plt.show()

from google.colab import files

# Pehle model ko Colab ke temporary storage mein save karo
best_xgb.save_model('transferiq_model.json')

# Phir usko apne local system par download karne ka prompt trigger karo
files.download('transferiq_model.json')