# -*- coding: utf-8 -*-
"""sentiment-Anaylysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1db3z2v79KXnS-Ixx2NV1a5Cbkd3H6oMi
"""

!pip install requests pandas textblob tqdm

import pandas as pd
import requests
from textblob import TextBlob
import time
from google.colab import files
from tqdm import tqdm

# 1. File Upload
print("📁 Apni file select karein...")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

def fetch_sentiment_stable(player_name):
    # Google News RSS (Ye block nahi hota aur real-time sentiment deta hai)
    url = f"https://news.google.com/rss/search?q={player_name}+football+performance"

    try:
        r = requests.get(url, timeout=10)
        # XML se headlines nikalne ka simple logic
        headlines = r.text.split('<title>')[1:6] # Top 5 news headlines

        if not headlines:
            return 0.0, "Neutral"

        scores = []
        for h in headlines:
            clean_text = h.split('</title>')[0]
            scores.append(TextBlob(clean_text).sentiment.polarity)

        avg = sum(scores) / len(scores)
        label = "Positive" if avg > 0.05 else ("Negative" if avg < -0.05 else "Neutral")
        return round(avg, 3), label
    except:
        return 0.0, "Error"

# 2. Main Logic with Live Logs
df = pd.read_csv(file_name)
results = []
total = len(df)

print(f"\n🚀 Analysis Shuru (Stable Mode)... Total Players: {total}")
print(f"{'-'*70}")
print(f"{'No.':<5} | {'Player Name':<25} | {'Score':<8} | {'Status'}")
print(f"{'-'*70}")

for i, row in df.iterrows():
    p_name = str(row['name'])
    score, label = fetch_sentiment_stable(p_name)

    # Live Terminal Display 🖥️
    print(f"{i+1:<5} | {p_name[:24]:<25} | {score:<8} | {label}")

    results.append({
        'player_id': row['player_id'],
        'sentiment_score': score,
        'sentiment_label': label
    })

    # News scraping fast hai, toh delay kam bhi chalega ⚡
    time.sleep(0.5)

# 3. Final Merge & Download
sentiment_df = pd.DataFrame(results)
final_df = pd.merge(df, sentiment_df, on='player_id', how='left')
final_df.to_csv('player_sentiment_final_stable.csv', index=False)
files.download('player_sentiment_final_stable.csv')

print("\n\n✅ Mission Accomplished! Data fetch ho gaya hai. 🔥")

import pandas as pd
from google.colab import files

# 1. 'player_sentiment_final_stable.csv' file upload karein
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# 2. Sirf wahi columns jo aapne maange hain
columns_to_keep = [
    'player_id', 'name', 'position', 'age', 'career_span_years',
    'peak_value_eur', 'value_cagr', 'value_multiplier_x',
    'post_peak_decline_pct', 'goals', 'assists', 'minutes_played',
    'days_missed', 'games_missed', 'sentiment_score',
    'sentiment_label', 'current_value_eur'
]

# 3. Filtering logic
df_final = df[columns_to_keep]

# 4. Result check aur download
print("\n✨ Cleaned Data Preview:")
print(df_final.head())

df_final.to_csv('final_sentiment_analysis_report.csv', index=False)
files.download('final_sentiment_analysis_report.csv')

import pandas as pd
from google.colab import files

# 1. Pehle original results wali file upload karein
print("📁 'player_sentiment_final_stable.csv' upload karein:")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# 2. File load karein
df_full = pd.read_csv(file_name)

# 3. Sirf sentiment wale columns select karein
# player_id zaroori hai taaki data identify ho sake
columns_to_extract = ['player_id', 'name', 'sentiment_score', 'sentiment_label']

# 4. Naya DataFrame banayein
df_sentiment_only = df_full[columns_to_extract]

# 5. Save aur Download
output_file = 'only_sentiment_data.csv'
df_sentiment_only.to_csv(output_file, index=False)
files.download(output_file)

print(f"\n✅ Success! Sirf sentiment wali file '{output_file}' download ho gayi hai. 🔥")

import matplotlib.pyplot as plt
import seaborn as sns

# Result load karein
res_df = pd.read_csv('player_sentiment_final_stable.csv')

# Plotting
plt.figure(figsize=(10,6))
sns.countplot(data=res_df, x='sentiment_label', palette='viridis')
plt.title('Distribution of Football Player Sentiments')
plt.xlabel('Sentiment Category')
plt.ylabel('Number of Players')
plt.show()

top_positive = res_df.sort_values(by='sentiment_score', ascending=False).head(10)
print("Top 10 Most Positive Players:")
print(top_positive[['name', 'sentiment_score']])

